// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI.DataModels;

public partial class articulo
{
    public int id_articulo { get; set; }

    public string Descripcion { get; set; }

    public int? precio { get; set; }

    public virtual ICollection<detallesFactura> detallesFacturas { get; set; } = new List<detallesFactura>();
}