// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI.DataModels;

public partial class detallesFactura
{
    public int id_detalle { get; set; }

    public int? nro_factura { get; set; }

    public int? id_articulo { get; set; }

    public int? cantidad { get; set; }

    public int? precio { get; set; }

    public virtual articulo id_articuloNavigation { get; set; }

    public virtual factura nro_facturaNavigation { get; set; }
}