// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI.DataModels;

public partial class factura
{
    public int nro_factura { get; set; }

    public DateTime? fecha { get; set; }

    public int? id_formaPago { get; set; }

    public string cliente { get; set; }

    public virtual ICollection<detallesFactura> detallesFacturas { get; set; } = new List<detallesFactura>();

    public virtual formasPago id_formaPagoNavigation { get; set; }
}