// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FacturacionAPI.DataModels;

public partial class FacturacionContext : DbContext
{
    public FacturacionContext(DbContextOptions<FacturacionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<articulo> articulos { get; set; }

    public virtual DbSet<detallesFactura> detallesFacturas { get; set; }

    public virtual DbSet<factura> facturas { get; set; }

    public virtual DbSet<formasPago> formasPagos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<articulo>(entity =>
        {
            entity.HasKey(e => e.id_articulo).HasName("pk_articulo");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<detallesFactura>(entity =>
        {
            entity.HasKey(e => e.id_detalle).HasName("pk_detalle");

            entity.HasOne(d => d.id_articuloNavigation).WithMany(p => p.detallesFacturas)
                .HasForeignKey(d => d.id_articulo)
                .HasConstraintName("fk_detalle_articulo");

            entity.HasOne(d => d.nro_facturaNavigation).WithMany(p => p.detallesFacturas)
                .HasForeignKey(d => d.nro_factura)
                .HasConstraintName("fk_detalle_factura");
        });

        modelBuilder.Entity<factura>(entity =>
        {
            entity.HasKey(e => e.nro_factura).HasName("pk_factura");

            entity.Property(e => e.cliente)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.fecha).HasColumnType("datetime");

            entity.HasOne(d => d.id_formaPagoNavigation).WithMany(p => p.facturas)
                .HasForeignKey(d => d.id_formaPago)
                .HasConstraintName("fk_factura_formaPago");
        });

        modelBuilder.Entity<formasPago>(entity =>
        {
            entity.HasKey(e => e.id_formaPago).HasName("pk_fomraPago");

            entity.ToTable("formasPago");

            entity.Property(e => e.nombre)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}