// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI.DataModels;

public partial class formasPago
{
    public int id_formaPago { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<factura> facturas { get; set; } = new List<factura>();
}